// Traveler's choice không có sản phẩm balo
// import btn_subMenu from "../category/btn_subMenu.js";
import loadProducts from "../function/load_product.js";


const tuiXach = [
    {
        "id": 45,
        "name": "Túi du lịch Minter",
        "brand": "SAMSONITE",
        "SKU": "HH5*74005",
        "image": "https://product.hstatic.net/200000117085/product/xanhneon_tuidulich_1_8c0d7b53ed7a42bc9b301e57fe257b49_master.jpg",
        "category": "Túi xách",
        "type" : "Túi du lịch",
        "size": "Túi du lịch",
        "color": "#008000",
        "price": 3200000,
        "inventory": "Còn hàng",
  
        "incart": 0,
        "description": "Thiết kế tối giản, sang trọng và được chế tạo với công nghệ vải RECYCLEX™, bộ sưu tập Minter từ Samsonite chính là sản phẩm hoàn hảo dành cho những du khách hiện đại và có ý thức với môi trường. Chiếc túi du lịch vỏ nhựa mới của bộ sưu tập Minter với các đường rãnh dọc tinh xảo và thanh logo dài bằng nhôm chạy ngang thân thể hiện sự sang trọng và tinh tế. Góp phần bảo vệ môi trường với lớp lót nội thất bằng vải jacquard chất lượng cao được tái chế từ 100% chai PET.",
        "status": "new",
    },
    {
        "id": 46,
        "name": "Túi du lịch Willcarl",
        "brand": "ACE. TOKYO",
        "SKU": "5560900-05",
        "image": "https://product.hstatic.net/200000117085/product/tim_tuixach_1_51896b64e1884f568a2c6cd7facd7e4f_master.jpg",
        "category": "Túi xách",
        "type" : "Túi du lịch",
        "size": "Túi du lịch",
        "color": "#800080",
        "price": 4500000,
        "inventory": "Hết hàng",
        "incart": 0,
        "description": "Một chiếc túi xách hoàn hảo để sử dụng cho một chuyến du lịch. Được làm bằng chất liệu nhẹ với họa tiết jacquard thanh lịch. Các ngăn có khóa kéo ở mặt trước và mặt sau của khoang chứa chính có độ mở tốt đủ lớn để vừa các sách hướng dẫn khổ A4, kèm theo một chiếc ví nhỏ để chứa giấy tờ và những vật có giá trị. Có hai túi ở bên hông. Sản phẩm đi kèm với dây đeo có thể tháo rời để sử dụng như một chiếc túi đeo vai. Tích hợp tính năng đai gài cần đẩy vali giúp bạn rảnh tay khi di chuyển.",
        "status": "new",
    },
    {
        "id": 47,
        "name": "Túi duffle kéo Raspail",
        "brand": "DELSEY",
        "SKU": "00328921000",
        "image": "https://product.hstatic.net/200000117085/product/do_tuikeo_1_5d0dfef8f20f4c629796ea70ce1849cc_master.jpg",
        "category": "Túi xách",
        "type" : "Túi du lịch",
        "size": "Túi du lịch",
        "color": "#800000",
        "price": 4800000,
        "inventory": "Hết hàng",
        "incart": 0,
        "description": "Bộ sưu tập Delsey Raspail được thiết kế dành riêng cho những du khách yêu thích phiêu lưu mạo hiểm. Những chiếc túi được làm từ chất liệu chống nước này sẽ đi khắp mọi nơi cùng bạn, và giữ cho hành lý được bảo vệ trong bất kể điều kiện nào. Với thiết kế thực dụng, có nhiều tay cầm và túi để đồ, bộ sưu tập Raspail từ thương hiệu Delsey Paris này sẽ giúp bạn hoàn toàn yên tâm trong tất cả các chuyến hành trình.",
        "status": "sale",
    },
    {
        "id": 48,
        "name": "Túi đeo chéo Cruise On The Go",
        "brand": "PACSAFE",
        "SKU": "20705329",
        "image": "https://product.hstatic.net/200000117085/product/tim_tuideocheo_1_581e5e095de045d0a2a5f12a3e44229a_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo chéo",
        "size": "Túi đeo chéo",
        "color": "#800080",
        "price": 1800000,
        "inventory": "Còn hàng",
        "incart": 0,
        "description": "Chiếc túi đeo chéo Cruise On The Go này là một phụ kiện tuyệt vời khi đi du lịch, phù hợp với các nhu yếu phẩm như điện thoại, túi trang điểm và nhiều thứ khác. Tất cả mọi thứ được sắp xếp trong túi gọn gàng, được bảo vệ bởi các tính năng bảo mật chống trộm thông minh từ Pacsafe.",
        "status": "sale",
    },
    {
        "id": 49,
        "name": "Túi đeo chéo Multitide 67581",
        "brand": "ACE. TOKYO",
        "SKU": "67581-01",
        "image": "https://product.hstatic.net/200000117085/product/den_tuideocheo_1_dacb79169e7242cb9cb16d08fb5979c1_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo chéo",
        "size": "Túi đeo chéo",
        "color": "#000000",
        "price": 3000000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Multitide là một bộ sưu tập balo và túi đeo chéo công sở được trang bị khả năng chống thấm nước, nhờ được làm bằng vật liệu và cấu trúc khiến nước mưa và bụi khó xâm nhập, cùng với thiết kế giúp tối ưu sự thoải mái khi sử dụng.",
    },
    {
        "id": 50,
        "name": "Túi đeo chéo Urban Packer",
        "brand": "SAMSONITE",
        "SKU": "HU5*09001",
        "image": "https://product.hstatic.net/200000117085/product/den_tuideocheo_1_3e210faba4cc42c4871ea3149c152ff9_a04aa6d5109e4dbeb129787e3066bafc_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo chéo",
        "size": "Túi đeo chéo",
        "color": "#000000",
        "price": 2100000,
        "inventory": "Hết hàng",
        "status": "",
        "incart": 0,
        "description": "Đáp ứng những yêu cầu về một bộ sưu tập bắt kịp với một thế giới luôn thay đổi, chiếc túi đeo chéo Urban Packer đã được thiết kế cho hiện tại và tương lai. Với chất liệu vải kháng khuẩn, ngăn đựng khẩu trang chuyên dụng, nhiều túi đựng các vật dụng cá nhân, chiếc túi này là người bạn đồng hành đáng tin cậy cho những chuyến du lịch hàng ngày.",
    },
    {
        "id": 51,
        "name": "Túi tote Batison",
        "brand": "CARLTON",
        "SKU": "QL6*09002",
        "image": "https://product.hstatic.net/200000117085/product/den_tote_1_12659b0aca0c4ef88b738db0e15ed15a_659db535918a4b00ac52848d06aeb9cb_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo chéo",
        "size": "Túi đeo chéo",
        "color": "#000000",
        "price": 3800000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Bộ sưu tập Batison là dòng sản phẩm dành riêng cho phái đẹp với phong cách thiết kế tối giản.",
    },
    {
        "id": 52,
        "name": "Túi đeo chéo Latha",
        "brand": "CARLTON",
        "SKU": "QL0*01002",
        "image": "https://product.hstatic.net/200000117085/product/xanhnhat_minicross_1_3a45e87e4a304b8195f202fdcbd609de_f9fb2c8b3bdc446c88293635077849f4_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo chéo",
        "size": "Túi đeo chéo",
        "color": "#0000FF",
        "price": 3200000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Samsonite Red LATHA là dòng túi sử dụng hàng ngày, có thể chứa những vật dụng cần thiết một cách tiện lợi và đơn giản.",
    },
    {
        "id": 53,
        "name": "Túi đeo chéo Dumfri",
        "brand": "CARLTON",
        "SKU": "QK5*83002",
        "image": "https://product.hstatic.net/200000117085/product/be_slingbag_1_19f33ac8b1c243b5b87a2960224cbafe_ca745391f7be488e82f8523cff4ad9dd_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo chéo",
        "size": "Túi đeo chéo",
        "color": "#996600",
        "price": 2200000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Dumfri là bộ sưu tập balo và túi xách sử dụng hàng ngày với thiết kế phong cách đường phố tự do và phóng khoáng, với các chi tiết vải được nhấn mạnh nổi bật.",
    },
    {
        "id": 54,
        "name": "Túi đeo Deluxe Security Pouch",
        "brand": "KAMILIANT",
        "SKU": "31171901",
        "image": "https://product.hstatic.net/200000117085/product/den_tuideoco_1_e027eb75746c4ae8812bf8d5b9412857_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo chéo",
        "size": "Túi đeo chéo",
        "color": "#000000",
        "price": 1000000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Cho dù bạn đi du lịch một mình hoặc với bạn bè và gia đình, hãy sắp xếp tất cả giấy tờ tùy thân cần thiết vào chiếc túi đeo bảo mật Deluxe Security Pouch đến từ thương hiệu Victorinox (Thụy Sỹ) và đeo nó bên mình để thuận tiện và bảo mật tối đa. Các giấy tờ của bạn dễ dàng truy cập, nhưng chỉ cho bạn và chỉ một mình bạn. Đây là sản phẩm sẽ luôn đồng hành cùng bạn trên mọi chuyến hành trình.",
    },
    {
        "id": 55,
        "name": "Túi clutch Chatelet Air 2.0",
        "brand": "DELSEY",
        "SKU": "00167611515",
        "image": "https://product.hstatic.net/200000117085/product/hong_clutch_1_6a0cc83770854c17a92222c47af6ea59_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo vai",
        "size": "Túi đeo vai",
        "color": "#FF00FF",
        "price": 3400000,
        "inventory": "Hết hàng",
        "status": "",
        "incart": 0,
        "description": "Bộ sưu tập Chatelet Air 2.0 là biểu tượng của văn hóa và sự sang trọng của nước Pháp. Thiết kế của bộ sưu tập gợi lên những hình ảnh kiến trúc truyền thống Paris. Những đường nét độc đáo gợi nhớ đến thiết kế cổ điển của hành lý trong quá khứ, đồng thời mang đến cho bộ sưu tập một vẻ ngoài đương đại.",
    },
    {
        "id": 56,
        "name": "Túi mini reporter 2-cpt Picpus",
        "brand": "TRAVELER'S CHOICE",
        "SKU": "3354113-10",
        "image": "https://product.hstatic.net/200000117085/product/den_tuitablet101in_1_0df845ad38ab478e989df5aae9f75e66.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo vai",
        "size": "Túi đeo vai",
        "color": "#000000",
        "price": 1400000,
        "inventory": "Hết hàng",
        "status": "",
        "incart": 0,
        "description": "Túi đeo Picpus mini reporter 10.1'' này sẽ là phụ kiện hàng ngày yêu thích của bạn. Bên trong túi có ngăn lưu trữ an toàn cho máy tính bảng 10.1'' và các phụ kiện điện tử khác. . Đây chính là chiếc túi cần thiết cho tất cả các chuyến hành trình của bạn!",
    },
    {
        "id": 57,
        "name": "Túi mini 2-cpt Picpus",
        "brand": "TRAVELER'S CHOICE",
        "SKU": "3354111-00*05001",
        "image": "https://product.hstatic.net/200000117085/product/den_tuimini_1_cfbf37d3f78845c2a6d3b049d3ca49cd_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo vai",
        "size": "Túi đeo vai",
        "color": "#000000",
        "price": 1400000,
        "inventory": "Hết hàng",
        "status": "",
        "incart": 0,
        "description": "Túi mini Picpus đảm bảo sự thoải mái tối ưu với dây đeo vai được thiết kế đặc biệt để sử dụng thường xuyên. Với 2 ngăn chứa rộng rãi có thể lưu trữ tất cả phụ kiện và chiếc tablet của bạn. Đây chính là chiếc túi cần phải có cho những chuyến hành trình!",
    },
    {
        "id": 58,
        "name": "Túi flat mini reporter Picpus",
        "brand": "TRAVELER'S CHOICE",
        "SKU": "3354109-00",
        "image": "https://product.hstatic.net/200000117085/product/den_tuitablet97in_1_fa6ceb2ece3e42c3bdc5c7d63e1651a5_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo vai",
        "size": "Túi đeo vai",
        "color": "#000000",
        "price": 1200000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Túi mini Picpus đảm bảo sự thoải mái tối ưu với dây đeo vai được thiết kế đặc biệt để sử dụng thường xuyên. Với 2 ngăn chứa rộng rãi có thể lưu trữ tất cả phụ kiện và chiếc tablet của bạn. Đây chính là chiếc túi cần phải có cho những chuyến hành trình!",
    },
    {
        "id": 59,
        "name": "Túi tote Batison",
        "brand": "WENGER",
        "SKU": "QL6*09002",
        "image": "https://product.hstatic.net/200000117085/product/den_tote_1_12659b0aca0c4ef88b738db0e15ed15a_659db535918a4b00ac52848d06aeb9cb_master.jpg",
        "category": "Túi xách",
        "type" : "Túi xách tay",
        "size": "Túi xách tay",
        "color": "#000000",
        "price": 3800000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Bộ sưu tập Batison là dòng sản phẩm dành riêng cho phái đẹp với phong cách thiết kế tối giản.",
    },
    {
        "id": 60,
        "name": "Túi xách Biena2 62554",
        "brand": "WENGER",
        "SKU": "62554-01",
        "image": "https://product.hstatic.net/200000117085/product/den_tuixach_1_e923304b694f4c6f9fbf21960a4e19d4_master.jpg",
        "category": "Túi xách",
        "type" : "Túi xách tay",
        "size": "Túi xách tay",
        "color": "#000000",
        "price": 5800000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Bộ sưu tập Batison là dòng sản phẩm dành riêng cho phái đẹp với phong cách thiết kế tối giản.",
    },
    {
        "id": 61,
        "name": "Túi xách My Wenger",
        "brand": "WENGER",
        "SKU": "CG1*50001",
        "image": "https://product.hstatic.net/200000117085/product/do_tuixachtay_1_36d0ec20366e4e89a8c8a8321230db64_master.jpg",
        "category": "Túi xách",
        "type" : "Túi xách tay",
        "size": "Túi xách tay",
        "color": "#FF00FF",
        "price": 4900000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Cổ điển, tối giản và hiện đại. BST My Wenger mang đến phong cách cá nhân hoàn hảo cho phái đẹp. Đơn sắc với các đường vân tự nhiên trên sản phẩm kết hợp thiết kế cột thắt cách điệu tạo điểm nhấn mang phong cách sang trọng, quý phái.",
    },
    {
        "id": 62,
        "name": "Túi đeo vai Mia",
        "brand": "AMERICAN TOURISTER",
        "SKU": "HL6*90003",
        "image": "https://product.hstatic.net/200000117085/product/nude_tuideo_1_d191c650b8dd479c8b7e3e2771ecfe7a_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo vai",
        "size": "Túi đeo vai",
        "color": "#996600",
        "price": 1100000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Mia từ thương hiệu American Tourister là bộ sưu tập hàng ngày với trọng lượng nhẹ dành cho những bạn nữ trẻ và năng động. Có 3 màu thời trang dễ dàng phù hợp với trang phục của bạn.",
    },
    {
        "id": 63,
        "name": "Túi đeo vai Kris",
        "brand": "AMERICAN TOURISTER",
        "SKU": "HC6*40001",
        "image": "https://product.hstatic.net/200000117085/product/hong_tuitienich_1_c72b779a17f44910a49ff300c2ad3176_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo vai",
        "size": "Túi đeo vai",
        "color": "#FF00FF",
        "price": 860000,
        "inventory": "Còn hàng",
        "status": "",
        "incart": 0,
        "description": "Được thiết kế tối giản và dễ dàng truy cập, túi đeo vai Kris được hoàn thiện tinh tế bằng vật liệu chống thấm nước bền chắc để bảo vệ các vật dụng thiết yếu của bạn. Với khối lượng nhẹ và khả năng lưu trữ lớn, túi có thể dễ dàng mang theo mọi nơi trong khi vẫn giữ các vật dụng cá nhân của bạn được ngăn nắp. Ngăn chính có đệm bảo vệ các thiết bị điện tử khi đang di chuyển. Kris là sự lựa chọn hoàn hảo cho các du khách hiện đại.",
    },
    {
        "id": 64,
        "name": "Cặp xách Speedair",
        "brand": "AMERICAN TOURISTER",
        "SKU": "23Z*09010",
        "image": "https://product.hstatic.net/200000117085/product/den_cap3way_1_74b69a9309c94b4783f226242eb929f5_master.jpg",
        "category": "Túi xách",
        "type" : "Túi đeo vai",
        "size": "Túi đeo vai",
        "color": "#000000",
        "price": 2200000,
        "inventory": "Hết hàng",
        "status": "",
        "incart": 0,
        "description": "BST Speedair từ American cung cấp trọn bộ cặp táp, balo cho các quý ông công sở. Nội thất nhiều ngăn với ngăn chứa riêng kèm lớp đệm cho laptop 15.4' 'và tablet đến 10.1'' tiện dụng cho các chuyến công tác hay những ngày làm việc thông thường. ",
    },
    {
        "id": 65,
        "name": "Túi tote Biena2 62553",
        "brand": "KAMILIANT",
        "SKU": "62553-01",
        "image": "https://product.hstatic.net/200000117085/product/xanhduong_tuitote_1_fcb2c170d9d44618b03747df77085a55_master.jpg",
        "category": "Túi xách",
        "type" : "Túi xách tay",
        "size": "Túi xách tay",
        "color": "#0000FF",
        "price": 5600000,
        "inventory": "Hết hàng",
        "status": "",
        "incart": 0,
        "description": "Bộ sưu tập ace. Biena2 là dòng sản phẩm 'Work Style Beauties Series', một chiếc túi công sở thanh lịch, tinh tế dành cho các nữ doanh nhân thành đạt.",
    },
]

loadProducts(tuiXach);
